### ISSUE TITLE
Not opening, rendering and creating table properly

### ISSUE THREAD

**Issue by Gourav1910** [trey-wallis/obsidian-dashboards#605] opened 2023-07-05 12:35 UTC
### Describe the bug

Hi first of all your plugin is amazing but I am facing various issues:

1) I created a dashboard table and then I embed it in a note and it embedded. But when I embed it second time (keep the first embed there) it is not rendering. It is not even rendering/embedding in another file. The thing why it is important to render a single table more than one time is because suppose I have a big dataset and I want to see it in various way by applying various filters so it is not happening right now.

![image](https://github.com/trey-wallis/obsidian-dashboards/assets/101202140/0d4d34a8-473d-4950-9a85-1cb790501573)
This is what it is rendering a blank table the second time. When I delete the first table/dashboard then the second one then rendered properly.

2) Second problem I am facing is when I am creating a new dashboard from the command which let me embed the dashboard in the current file with creating the dashboard itself. But when I am creating it it doesn't render the table there. I have to refresh the note to see the rendered table.

3) I am not able to directly open the dashboard/table file from the file explorer of obsidian. When I am clicking on it it just doing nothing. It means I can't directly open the main dashboard file. I can only open it in embed and that too only one time. 

4) In reading mode it is not rendering anything. It is only rendering the table in live preview mode.

### Steps to reproduce

I don't exactly know what does this mean. But let me record the screen while doing all the things which will cover all the issues.

It seems like file size is big of recorded file so I have uploaded it on google drive. Here is the link to watch that short video.
https://drive.google.com/file/d/1pgDVwAEBTxCBN3V_MQw3tbgNleN1onZS/view?usp=sharing

### Expected behavior

I am seeing this plugin as an alternative to notion tables. I want to use it like an inline table anywhere I want to create it or embed it. And also I want to see it in reading view also. I want to open the dashboard file seperately as well. I want to embed one single file several times by applying different filters in each embed which will make it more useful.

I have you look into these issues and fix it🙏🙏.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: AnuPpuccin v1.3.1
	Snippets enabled: 17
	Restricted mode: off
	Plugins installed: 62
	Plugins enabled: 34
		1: Obsidian Git v2.20.5
		2: Excalidraw v1.9.7
		3: Fullscreen mode plugin v0.1.2
		4: Recent Files v1.3.6
		5: Tag Wrangler v0.5.11
		6: Calendar v1.5.10
		7: Periodic Notes v0.0.17
		8: Minimal Theme Settings v6.3.1
		9: Commander v0.5.0
		10: Projects v1.16.0
		11: Timestamp Notes v1.0.8
		12: Open Gate v1.8.4
		13: Kanban v1.5.3
		14: QuickAdd v1.2.1
		15: MetaEdit v1.8.0
		16: Banners v1.3.3
		17: Image Gallery v1.1.1
		18: Templater v1.16.0
		19: Home tab v1.1.2
		20: Spaced Repetition v1.10.1
		21: Dataview v0.5.56
		22: Tasks v4.1.0
		23: Surfing v0.8.16
		24: Custom Frames v2.4.6
		25: Telegram Sync v1.7.1
		26: obsidian markmind v1.7.4
		27: Style Settings v1.0.6
		28: Paste URL into selection v1.7.0
		29: Charts View v1.2.5
		30: Link with alias v1.0.5
		31: Obsidian Leaflet v5.7.1
		32: Simple Embeds v1.14.1
		33: Settings Search v1.3.7
		34: Dashboards v7.0.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by qf3l3k** [comment] 2023-07-05 15:29
I have similar issue.
When new file with table is created filename has extension .table, so it is not opened correctly.
Once file is renamed to .dashboard it can be opened without any issues.
Just simple issue with incorrect extension being added to filename when creating dashboard.

**Comment by Gourav1910** [comment] 2023-07-05 18:01
> I have similar issue. When new file with table is created filename has extension .table, so it is not opened correctly. Once file is renamed to .dashboard it can be opened without any issues. Just simple issue with incorrect extension being added to filename when creating dashboard.

Yeah changing the extension fixed the file opening issue but now it is not embedding it.

**Comment by trey-wallis** [comment] 2023-07-05 19:34
@Gourav1910 Thanks for this report. 1,2,3 have been fixed in 7.0.1. For 4, please see #513

**Closed by trey-wallis** 2023-07-05 19:34 UTC
Labels: bug

**Comment by Gourav1910** [comment] 2023-07-05 20:35
> @Gourav1910 Thanks for this report. 1,2,3 have been fixed in 7.0.1. For 4, please see #513

Hi thanks for updating it. I just checked it and the issue 2 and 3 is fixed but issue 1 is not fixed yet. It is still not rendering one dashboard more than one time. It is rendering blank like I shown in the screenshot above. When I delete the first rendered/embedded dashboard then it automatically render the second. Please fix this issue as well.

**Comment by trey-wallis** [comment] 2023-07-05 21:26
@Gourav1910 Could you give me some more information to help me debug it? What are the names of the tables that you are trying to embed? And what are the link names? Could you maybe send a video.

**Comment by Gourav1910** [comment] 2023-07-05 22:20
> @Gourav1910 Could you give me some more information to help me debug it? What are the names of the tables that you are trying to embed? And what are the link names? Could you maybe send a video.

so my file name is "untitled 1.dashboard". I embedded it twice in a note. So the first one rendered properly and second one is showing blank. Here is a screenshot of that note.

![image](https://github.com/trey-wallis/obsidian-dashboards/assets/101202140/b6916d8f-1af8-4a92-b173-3be203664cae)

If I delete the above embedded dashboard then immediately below one render. I have recorded a video. Here is the google drive link of the video.
https://drive.google.com/file/d/1ItdFW-i3g4ZSFtir3YPV1fTghLghbW9W/view?usp=sharing

**Comment by trey-wallis** [comment] 2023-07-05 22:51
Great. Thanks for sending for a video.

So to be short, this is not a bug. This is expected behavior. I stop a user from embedding the same table twice into the same file. The plugin currently doesn't have a view system to handle different filters. So you can't embed a table twice and set different filters on each one. They would both update the same file and show the same filters.
